---
- hosts: localhost
  vars:
   pkg: apache2
  tasks: 

  - name: installing "{{ pkg }}"
    package:
     name: "{{ pkg }}"
     state: latest
  - name: Restarting "{{ pkg }}"
    service:
     name: "{{ pkg }}"
     state: restarted
